#pragma once

/* Mouse Buttons */
#define MORP_MOUSE_BUTTON_1         0
#define MORP_MOUSE_BUTTON_2         1
#define MORP_MOUSE_BUTTON_3         2
#define MORP_MOUSE_BUTTON_4         3
#define MORP_MOUSE_BUTTON_5         4
#define MORP_MOUSE_BUTTON_6         5
#define MORP_MOUSE_BUTTON_7         6
#define MORP_MOUSE_BUTTON_8         7
#define MORP_MOUSE_BUTTON_LAST      MORP_MOUSE_BUTTON_8
#define MORP_MOUSE_BUTTON_LEFT      MORP_MOUSE_BUTTON_1
#define MORP_MOUSE_BUTTON_RIGHT     MORP_MOUSE_BUTTON_2
#define MORP_MOUSE_BUTTON_MIDDLE    MORP_MOUSE_BUTTON_3